<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Entrar</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input name="nome" value="<?= $this->view->valueCampos['nome']  ?>" type="text" class="form-control" placeholder="Nome">
              </div>
              
              <div class="form-group">
                <input name="email" value="<?= $this->view->valueCampos['email']  ?>" type="text" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input name="senha" value="<?= $this->view->valueCampos['senha']  ?>" type="password" class="form-control" placeholder="Senha">
              </div>

              <?php if(isset($this->view->usuarioExiste)) { ?>
                <small class="lead text-danger">Usuario já Existe, tente utilizar outro e-mail</small>
              <?php } ?>

              <?php if(isset($this->view->camposInvalidos)) { ?>
                <small class="lead text-danger">Houve um ero ao efetuar o cadastro, verifique se os campos estao preenchidos corretamente</small>
              <?php } ?>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  